export const StyleConstants = {
  colors: {
    blue: '#0815FF',
    yellow: '#F7BF31',
  },
};

export const APIConstants = {
  base: 'http://localhost:3002/'
};

export const ActionConstants = {
    UPDATE_BILL_STATUS: 'UPDATE_BILL_STATUS',
    FETCH_BILLS_DATA: 'FETCH_BILLS_DATA',
    FETCH_BILLS_DATA_SAGA: 'FETCH_BILLS_DATA_SAGA',
    FETCH_BILLS_DATA_SUCCESS: 'FETCH_BILLS_DATA_SUCCESS',
    FETCH_BILLS_DATA_FAILURE: 'FETCH_BILLS_DATA_FAILURE',
    FETCH_CATEGORIES_DATA: 'FETCH_CATEGORIES_DATA',
    FETCH_CATEGORIES_DATA_SAGA: 'FETCH_CATEGORIES_DATA_SAGA',
    FETCH_CATEGORIES_DATA_SUCCESS: 'FETCH_CATEGORIES_DATA_SUCCESS',
    FETCH_CATEGORIES_DATA_FAILURE: 'FETCH_CATEGORIES_DATA_FAILURE',
};